# Generated by Django 2.1.1 on 2018-10-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterfaceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdata',
            name='source',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
