# Generated by Django 2.1.1 on 2018-10-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterfaceapp', '0002_auto_20181029_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterDataRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField(default=0)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinterfaceapp.TwitterData')),
            ],
        ),
    ]
