# Generated by Django 2.1.1 on 2019-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterfaceapp', '0007_stockdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='symbol',
            field=models.TextField(default='2019-01-01 11.00', max_length=5000),
            preserve_default=False,
        ),
    ]
